# Generated by Django 3.1.5 on 2021-01-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_id', models.IntegerField()),
                ('roulette_id', models.IntegerField()),
                ('ammount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('funds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bets', models.IntegerField()),
                ('open', models.BooleanField()),
            ],
        ),
    ]
